import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Hornsby Area Daily Rainfall Forecasting: v2 (Interactive Global Climate Simulator)\n",
    "\n",
    "This notebook implements a state-of-the-art **Two-Stage Hurdle Machine Learning Model** combined with **Facebook Prophet** temperature forecasting, **Real-Time NOAA ENSO (NINO3.4) Global Climate Index Fetching**, and an **Interactive Stochastic Weather Generator (Monte Carlo Simulator)**.\n",
    "\n",
    "### Modeling Pipeline Key Highlights:\n",
    "1. **BOM Data Calibration (NaN to 0.0)**: Correctly identifies that blank/NaN entries in BOM tables during active recording months represent **dry days (0.0 mm of rainfall)**. Imputing this restores the authentic **33.56% rainy-day ratio** and resolves the 100% wet-day training bias.\n",
    "2. **Thermodynamic Predictors (Terrey Hills AWS)**: Aligns the Hornsby rainfall data with daily maximum and minimum temperatures from the geographically closest complete AWS station (Terrey Hills AWS).\n",
    "3. **Global Climate Index (NOAA NINO3.4)**: Real-time downloads monthly Oceanic Niño Index (NINO3.4 anomalies) from the NOAA Climate Prediction Center to incorporate the Pacific global atmospheric circulation state.\n",
    "4. **Absorbing Zero Trap Resolution**: Replaces the problematic deterministic thresholding with **Stochastic Bernoulli Sampling** combined with **Overcast temperature feedback** (reducing diurnal temperature range by 25% on rainy days to simulate cloud cover) and **calibrated meteorological residual noise** to simulate stable, highly realistic wet and dry spell successions.\n",
    "5. **Interactive \"What-If\" Climate Simulator**: Runs and compares three distinct future global climate scenarios for Hornsby daily rainfall: **La Niña** (heavy rain clusters), **Neutral** (climatological baseline), and **El Niño** (dry spell drought)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import io\n",
    "import json\n",
    "import requests\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.dates as mdates\n",
    "import seaborn as sns\n",
    "from xgboost import XGBClassifier, XGBRegressor\n",
    "from prophet import Prophet\n",
    "from sklearn.metrics import roc_auc_score, f1_score, mean_squared_error, mean_absolute_error, classification_report\n",
    "from sklearn.model_selection import TimeSeriesSplit\n",
    "\n",
    "# Set premium aesthetics plotting styles\n",
    "sns.set_theme(style=\"whitegrid\")\n",
    "plt.rcParams['figure.figsize'] = [12, 6]\n",
    "plt.rcParams['font.sans-serif'] = ['Arial', 'Helvetica']\n",
    "plt.rcParams['axes.unicode_minus'] = False"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Section 1: Preprocessing & Data Alignment"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def melt_df(df, val_name, fill_na=None):\n",
    "    \"\"\"\n",
    "    Cleans station names and melts the wide weather data (Day_1 to Day_31)\n",
    "    into a tidy long format, handling date conversions and invalid calendar dates.\n",
    "    \"\"\"\n",
    "    df = df.copy()\n",
    "    df['Station'] = df['Station'].str.replace(r'\\s+', ' ', regex=True).str.strip()\n",
    "    day_cols = [c for c in df.columns if c.startswith('Day_')]\n",
    "    \n",
    "    df_long = df.melt(\n",
    "        id_vars=['YearMonth', 'Station'],\n",
    "        value_vars=day_cols,\n",
    "        var_name='Day',\n",
    "        value_name=val_name\n",
    "    )\n",
    "    \n",
    "    df_long['Day'] = df_long['Day'].str.extract(r'(\\d+)').astype(int)\n",
    "    df_long['DateStr'] = df_long['YearMonth'].astype(str) + df_long['Day'].astype(str).str.zfill(2)\n",
    "    df_long['Date'] = pd.to_datetime(df_long['DateStr'], format='%Y%m%d', errors='coerce')\n",
    "    \n",
    "    # Drop rows with invalid calendar dates (e.g., Feb 30th)\n",
    "    df_long = df_long.dropna(subset=['Date']).drop(columns=['DateStr'])\n",
    "    df_long[val_name] = pd.to_numeric(df_long[val_name], errors='coerce')\n",
    "    \n",
    "    if fill_na is not None:\n",
    "        df_long[val_name] = df_long[val_name].fillna(fill_na)\n",
    "        \n",
    "    return df_long\n",
    "\n",
    "def load_and_clean_data():\n",
    "    \"\"\"\n",
    "    Loads raw CSV files, filters the specific stations (Hornsby for Rain, Terrey Hills for Temps),\n",
    "    and merges them into a clean daily time series.\n",
    "    \"\"\"\n",
    "    print(\"Loading raw CSV datasets...\")\n",
    "    df_max_raw = pd.read_csv('daily_max_temp.csv')\n",
    "    df_min_raw = pd.read_csv('daily_min_temp.csv')\n",
    "    df_rain_raw = pd.read_csv('daily_rainfall.csv')\n",
    "    \n",
    "    print(\"Melting and cleaning data frames...\")\n",
    "    df_max = melt_df(df_max_raw, 'MaxTemp')\n",
    "    df_min = melt_df(df_min_raw, 'MinTemp')\n",
    "    \n",
    "    # Crucial NaN repair step: fill NaN with 0.0 during active station months\n",
    "    df_rain = melt_df(df_rain_raw, 'Rainfall', fill_na=0.0)\n",
    "    \n",
    "    print(\"Filtering Terrey Hills AWS for temperature observations...\")\n",
    "    th_max = df_max[df_max['Station'] == 'Terrey Hills AWS'][['Date', 'MaxTemp']].copy()\n",
    "    th_min = df_min[df_min['Station'] == 'Terrey Hills AWS'][['Date', 'MinTemp']].copy()\n",
    "    \n",
    "    print(\"Filtering Hornsby (Swimming Pool) for rainfall observations...\")\n",
    "    h_rain = df_rain[df_rain['Station'] == 'Hornsby (Swimming Pool)'][['Date', 'Rainfall']].copy()\n",
    "    \n",
    "    # Interpolate temperature nulls (minor gaps in the observation series)\n",
    "    th_max = th_max.sort_values('Date').reset_index(drop=True)\n",
    "    th_min = th_min.sort_values('Date').reset_index(drop=True)\n",
    "    th_max['MaxTemp'] = th_max['MaxTemp'].interpolate(method='linear').ffill().bfill()\n",
    "    th_min['MinTemp'] = th_min['MinTemp'].interpolate(method='linear').ffill().bfill()\n",
    "    \n",
    "    print(\"Merging datasets into unified daily time series...\")\n",
    "    merged = pd.merge(th_max, th_min, on='Date', how='outer')\n",
    "    merged = pd.merge(merged, h_rain, on='Date', how='outer')\n",
    "    merged = merged.sort_values('Date').reset_index(drop=True)\n",
    "    \n",
    "    return merged\n",
    "\n",
    "master_df = load_and_clean_data()\n",
    "print(f\"Master aligned dataframe shape: {master_df.shape}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Section 2: Global Climate Driver Fetching (NOAA CPC NINO3.4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def fetch_and_merge_nino_features(df):\n",
    "    \"\"\"\n",
    "    Scrapes monthly Oceanic Niño Index (NINO3.4 anomalies) directly from NOAA CPC\n",
    "    and merges it into the local daily dataframe.\n",
    "    \"\"\"\n",
    "    url = \"https://www.cpc.ncep.noaa.gov/data/indices/sstoi.indices\"\n",
    "    print(f\"Fetching NINO3.4 Sea Surface Temperature Indices from NOAA CPC: {url}\")\n",
    "    \n",
    "    try:\n",
        "        headers = {'User-Agent': 'Mozilla/5.0'}\n",
        "        r = requests.get(url, headers=headers, timeout=15)\n",
        "        \n",
        "        if r.status_code != 200:\n",
        "            raise Exception(f\"NOAA CPC server returned status code {r.status_code}\")\n",
        "            \n",
        "        # Parse space-separated tables using io.StringIO\n",
        "        lines = [line for line in r.text.split('\\n') if line.strip()]\n",
        "        raw_df = pd.read_csv(io.StringIO('\\n'.join(lines)), sep=r'\\s+', engine='python')\n",
        "        \n",
        "        # Columns are YR, MON, NINO1+2, ANOM, NINO3, ANOM.1, NINO4, ANOM.2, NINO3.4, ANOM.3\n",
        "        nino_df = raw_df.iloc[:, [0, 1, 8, 9]].copy()\n",
        "        nino_df.columns = ['Year', 'Month', 'NINO3.4_SST', 'NINO3.4_Anom']\n",
        "        \n",
        "        nino_df['Year'] = nino_df['Year'].astype(int)\n",
        "        nino_df['Month'] = nino_df['Month'].astype(int)\n",
        "        nino_df['NINO3.4_Anom'] = pd.to_numeric(nino_df['NINO3.4_Anom'], errors='coerce')\n",
        "        \n",
        "        print(f\"Successfully parsed NOAA climate indices from {nino_df['Year'].min()} to {nino_df['Year'].max()}\")\n",
        "        \n",
        "        # Left-join into our master dataset based on Date's Year and Month\n",
        "        df = df.copy()\n",
        "        df['Year'] = df['Date'].dt.year\n",
        "        df['Month'] = df['Date'].dt.month\n",
        "        \n",
        "        merged = pd.merge(df, nino_df[['Year', 'Month', 'NINO3.4_Anom']], on=['Year', 'Month'], how='left')\n",
        "        merged['NINO3.4_Anom'] = merged['NINO3.4_Anom'].ffill().bfill() # Handle minor boundaries\n",
        "        \n",
        "        print(\"Successfully merged NINO3.4 Anomaly index into master data!\")\n",
        "        return merged.drop(columns=['Year'])\n",
        "        \n",
        "    except Exception as e:\n",
        "        print(f\"Warning: Failed to fetch global NOAA index due to: {e}.\")\n",
        "        print(\"Fallback: Imputing NINO3.4_Anom with neutral climate climatological mean (0.0)\")\n",
        "        df = df.copy()\n",
        "        df['NINO3.4_Anom'] = 0.0\n",
        "        return df\n",
    "\n",
    "master_df_enriched = fetch_and_merge_nino_features(master_df)\n",
    "master_df_enriched[['Date', 'MaxTemp', 'Rainfall', 'NINO3.4_Anom']].tail(5)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Section 3: Exploratory Data Analysis & Climate Correlations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def perform_eda(df):\n",
    "    h_data = df.dropna(subset=['Rainfall']).copy()\n",
    "    # Pre-calculate month and year columns for groupings\n",
    "    h_data['Year'] = h_data['Date'].dt.year\n",
    "    h_data['Month'] = h_data['Date'].dt.month\n",
    "    \n",
    "    total_days = len(h_data)\n",
    "    rainy_days = (h_data['Rainfall'] > 0).sum()\n",
    "    rain_ratio = rainy_days / total_days\n",
    "    \n",
    "    print(f\"Total historical days with rainfall observations: {total_days}\")\n",
    "    print(f\"Number of rainy days (> 0mm): {rainy_days} ({rain_ratio*100:.2f}%)\")\n",
    "    print(f\"Maximum daily rainfall recorded: {h_data['Rainfall'].max():.1f} mm\")\n",
    "    print(f\"Mean rainfall on rainy days: {h_data[h_data['Rainfall'] > 0]['Rainfall'].mean():.2f} mm\")\n",
    "    \n",
    "    # Generate premium charts\n",
    "    fig, axes = plt.subplots(2, 2, figsize=(18, 12))\n",
    "    \n",
    "    # Plot 1: Temperature, ENSO & Rainfall Correlation Heatmap\n",
    "    corr_df = h_data[['MaxTemp', 'MinTemp', 'Rainfall', 'NINO3.4_Anom']].copy()\n",
    "    corr_df['TempRange'] = corr_df['MaxTemp'] - corr_df['MinTemp']\n",
    "    sns.heatmap(corr_df.corr(), annot=True, cmap='coolwarm', fmt=\".3f\", ax=axes[0, 0], vmin=-1, vmax=1)\n",
    "    axes[0, 0].set_title('Correlation Matrix (Rain, Temps, and NOAA NINO3.4)', fontsize=14, pad=12)\n",
    "    \n",
    "    # Plot 2: Seasonal Rain Probability vs Intensity\n",
    "    monthly_stats = h_data.groupby('Month').agg(\n",
    "        RainProbability=('Rainfall', lambda x: (x > 0).mean()),\n",
    "        AvgRainfall=('Rainfall', 'mean')\n",
    "    ).reset_index()\n",
    "    \n",
    "    ax1 = axes[0, 1]\n",
    "    sns.barplot(data=monthly_stats, x='Month', y='RainProbability', color='#3498db', alpha=0.7, ax=ax1)\n",
    "    ax1.set_ylabel('Rain Probability', color='#3498db', fontsize=12)\n",
    "    ax1.tick_params(axis='y', labelcolor='#3498db')\n",
    "    ax1.set_title('Monthly Seasonal Rainfall Patterns', fontsize=14, pad=12)\n",
    "    \n",
    "    ax2 = ax1.twinx()\n",
    "    sns.lineplot(data=monthly_stats, x=monthly_stats['Month'] - 1, y='AvgRainfall', color='#e74c3c', marker='o', linewidth=2.5, ax=ax2)\n",
    "    ax2.set_ylabel('Average Daily Rainfall (mm)', color='#e74c3c', fontsize=12)\n",
    "    ax2.tick_params(axis='y', labelcolor='#e74c3c')\n",
    "    ax2.grid(False)\n",
    "    \n",
    "    # Plot 3: Non-Zero Rain Distribution (Log Scale)\n",
    "    positive_rain = h_data[h_data['Rainfall'] > 0]['Rainfall']\n",
    "    sns.histplot(positive_rain, bins=40, kde=True, log_scale=True, color='#2ecc71', ax=axes[1, 0])\n",
    "    axes[1, 0].set_title('Distribution of Non-Zero Daily Rainfall (Log Scale)', fontsize=14, pad=12)\n",
    "    axes[1, 0].set_xlabel('Rainfall (mm)')\n",
    "    axes[1, 0].set_ylabel('Density / Count')\n",
    "    \n",
    "    # Plot 4: ENSO Sea Surface Temperature Anomaly vs Monthly Rainfall\n",
    "    # Group by month to observe ENSO effect clearly\n",
    "    monthly_sums = h_data.groupby(['Year', 'Month']).agg(\n",
    "        MonthlyRainfall=('Rainfall', 'sum'),\n",
    "        NINO34_Mean=('NINO3.4_Anom', 'mean')\n",
    "    ).reset_index()\n",
    "    sns.scatterplot(data=monthly_sums, x='NINO34_Mean', y='MonthlyRainfall', color='#e67e22', s=70, alpha=0.8, ax=axes[1, 1])\n",
    "    sns.regplot(data=monthly_sums, x='NINO34_Mean', y='MonthlyRainfall', scatter=False, color='#2c3e50', ax=axes[1, 1])\n",
    "    axes[1, 1].set_title('NOAA NINO3.4 SST Anomaly vs Monthly Rainfall (mm)', fontsize=14, pad=12)\n",
    "    axes[1, 1].set_xlabel('Niño 3.4 SST Anomaly (°C) [Negative represents La Niña]')\n",
    "    axes[1, 1].set_ylabel('Total Monthly Rainfall (mm)')\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "perform_eda(master_df_enriched)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Section 4: Feature Engineering with Global Climate Index"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def engineer_features(df):\n",
    "    \"\"\"\n",
    "    Constructs robust features for ML modeling including cyclic temporal\n",
    "    encodings, temperature ranges, lags, and global ENSO climate index.\n",
    "    \"\"\"\n",
    "    data = df.copy().sort_values('Date').reset_index(drop=True)\n",
    "    \n",
    "    # 1. Date features\n",
    "    data['Month'] = data['Date'].dt.month\n",
    "    data['DayOfYear'] = data['Date'].dt.dayofyear\n",
    "    data['DayOfWeek'] = data['Date'].dt.dayofweek\n",
    "    \n",
    "    # 2. Cyclic calendar encodings\n",
    "    data['Month_Sin'] = np.sin(2 * np.pi * data['Month'] / 12)\n",
    "    data['Month_Cos'] = np.cos(2 * np.pi * data['Month'] / 12)\n",
    "    data['DayOfYear_Sin'] = np.sin(2 * np.pi * data['DayOfYear'] / 365.25)\n",
    "    data['DayOfYear_Cos'] = np.cos(2 * np.pi * data['DayOfYear'] / 365.25)\n",
    "    \n",
    "    # 3. Temperature features\n",
    "    data['TempRange'] = data['MaxTemp'] - data['MinTemp']\n",
    "    data['TempDeltaMax'] = data['MaxTemp'].diff().fillna(0)\n",
    "    data['TempDeltaMin'] = data['MinTemp'].diff().fillna(0)\n",
    "    \n",
    "    # Rolling averages of temperature (last 3 days)\n",
    "    data['MaxTemp_Roll3'] = data['MaxTemp'].rolling(window=3, min_periods=1).mean()\n",
    "    data['MinTemp_Roll3'] = data['MinTemp'].rolling(window=3, min_periods=1).mean()\n",
    "    data['TempRange_Roll3'] = data['TempRange'].rolling(window=3, min_periods=1).mean()\n",
    "    \n",
    "    # 4. Target variables\n",
    "    data['IsRainy'] = (data['Rainfall'] > 0).astype(int)\n",
    "    \n",
    "    # 5. Autoregressive lags for Rainfall\n",
    "    data['Rain_Lag1'] = data['Rainfall'].shift(1).fillna(0)\n",
    "    data['Rain_Lag2'] = data['Rainfall'].shift(2).fillna(0)\n",
    "    data['Rain_Lag3'] = data['Rainfall'].shift(3).fillna(0)\n",
    "    \n",
    "    return data\n",
    "\n",
    "df_ml = engineer_features(master_df_enriched)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Section 5: Daily Temperature Forecasting (Prophet)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_prophet_temp(df):\n",
    "    \"\"\"\n",
    "    Fits Prophet models to forecast MaxTemp and MinTemp for the next 1 year.\n",
    "    \"\"\"\n",
    "    df_max = df[['Date', 'MaxTemp']].rename(columns={'Date': 'ds', 'MaxTemp': 'y'}).dropna()\n",
    "    df_min = df[['Date', 'MinTemp']].rename(columns={'Date': 'ds', 'MinTemp': 'y'}).dropna()\n",
    "    \n",
    "    print(\"Fitting Prophet MaxTemp model...\")\n",
    "    model_max = Prophet(yearly_seasonality=True, weekly_seasonality=False, daily_seasonality=False)\n",
    "    model_max.fit(df_max)\n",
    "    \n",
    "    print(\"Fitting Prophet MinTemp model...\")\n",
    "    model_min = Prophet(yearly_seasonality=True, weekly_seasonality=False, daily_seasonality=False)\n",
    "    model_min.fit(df_min)\n",
    "    \n",
    "    # Predict 365 days into the future\n",
    "    last_date = df['Date'].max()\n",
    "    future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=365, freq='D')\n",
    "    future_df = pd.DataFrame({'ds': future_dates})\n",
    "    \n",
    "    print(\"Predicting daily temperatures for the next 12 months...\")\n",
    "    forecast_max = model_max.predict(future_df)[['ds', 'yhat']].rename(columns={'ds': 'Date', 'yhat': 'MaxTemp'})\n",
    "    forecast_min = model_min.predict(future_df)[['ds', 'yhat']].rename(columns={'ds': 'Date', 'yhat': 'MinTemp'})\n",
    "    \n",
    "    future_temp = pd.merge(forecast_max, forecast_min, on='Date')\n",
    "    \n",
    "    return future_temp\n",
    "\n",
    "future_temp = train_prophet_temp(df_ml)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Section 6: Two-Stage Hurdle Model Training & Calibrating"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "features = [\n",
    "    'Month', 'DayOfYear', 'DayOfWeek',\n",
    "    'Month_Sin', 'Month_Cos', 'DayOfYear_Sin', 'DayOfYear_Cos',\n",
    "    'TempRange', 'TempDeltaMax', 'TempDeltaMin',\n",
    "    'MaxTemp_Roll3', 'MinTemp_Roll3', 'TempRange_Roll3',\n",
    "    'Rain_Lag1', 'Rain_Lag2', 'Rain_Lag3',\n",
    "    'NINO3.4_Anom' # ENSO Index added to features list!\n",
    "]\n",
    "\n",
    "def train_and_eval_hurdle(df_ml, features):\n",
    "    train_data = df_ml.dropna(subset=['Rainfall']).copy()\n",
    "    X = train_data[features]\n",
    "    y_class = train_data['IsRainy']\n",
    "    y_reg = train_data['Rainfall']\n",
    "    \n",
    "    # Time series cross validation (5 folds)\n",
    "    tscv = TimeSeriesSplit(n_splits=5)\n",
    "    clf_rocs = []\n",
    "    reg_rmses = []\n",
    "    \n",
    "    print(\"Performing Time Series Cross-Validation...\")\n",
    "    for fold, (train_idx, val_idx) in enumerate(tscv.split(X)):\n",
    "        X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]\n",
    "        y_tr_c, y_val_c = y_class.iloc[train_idx], y_class.iloc[val_idx]\n",
    "        y_tr_r, y_val_r = y_reg.iloc[train_idx], y_reg.iloc[val_idx]\n",
    "        \n",
    "        clf_fold = XGBClassifier(n_estimators=120, learning_rate=0.03, max_depth=4, random_state=42, eval_metric='logloss')\n",
    "        clf_fold.fit(X_tr, y_tr_c)\n",
    "        val_preds_prob = clf_fold.predict_proba(X_val)[:, 1]\n",
    "        roc = roc_auc_score(y_val_c, val_preds_prob)\n",
    "        clf_rocs.append(roc)\n",
    "        \n",
    "        rainy_tr = y_tr_c == 1\n",
    "        rainy_val = y_val_c == 1\n",
    "        if rainy_tr.sum() > 10 and rainy_val.sum() > 0:\n",
    "            reg_fold = XGBRegressor(n_estimators=120, learning_rate=0.03, max_depth=4, random_state=42)\n",
    "            reg_fold.fit(X_tr[rainy_tr], y_tr_r[rainy_tr])\n",
    "            val_preds_r = reg_fold.predict(X_val[rainy_val])\n",
    "            rmse = np.sqrt(mean_squared_error(y_val_r[rainy_val], val_preds_r))\n",
    "            reg_rmses.append(rmse)\n",
    "            print(f\"  Fold {fold+1} - Class ROC-AUC: {roc:.3f} | Reg RMSE: {rmse:.2f} mm\")\n",
    "            \n",
    "    print(f\"\\nAverage CV Metrics:\\n  Classifier ROC-AUC: {np.mean(clf_rocs):.3f}\\n  Regressor Positive RMSE: {np.mean(reg_rmses):.2f} mm\")\n",
    "    \n",
    "    # Train final models\n",
    "    print(\"\\nTraining final models on complete enriched historical dataset...\")\n",
    "    clf = XGBClassifier(n_estimators=120, learning_rate=0.03, max_depth=4, subsample=0.8, colsample_bytree=0.8, random_state=42, eval_metric='logloss')\n",
    "    clf.fit(X, y_class)\n",
    "    \n",
    "    reg = XGBRegressor(n_estimators=120, learning_rate=0.03, max_depth=4, subsample=0.8, colsample_bytree=0.8, random_state=42)\n",
    "    reg.fit(X[y_class == 1], y_reg[y_class == 1])\n",
    "    \n",
    "    # Feature Importances\n",
    "    importances = pd.DataFrame({\n",
    "        'Feature': features,\n",
    "        'Classifier_Importance': clf.feature_importances_,\n",
    "        'Regressor_Importance': reg.feature_importances_\n",
    "    }).sort_values('Classifier_Importance', ascending=False)\n",
    "    print(\"\\nFeature Importances:\")\n",
    "    print(importances.to_string(index=False))\n",
    "    \n",
    "    return clf, reg\n",
    "\n",
    "clf, reg = train_and_eval_hurdle(df_ml, features)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Section 7: Recursive Simulation with \"What-If\" Climate Scenarios"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def predict_future_recursive(df_ml, future_temp, clf, reg, features, nino_scenario=0.0):\n",
    "    \"\"\"\n",
    "    Performs dynamic recursive weather simulation. The future NOAA NINO3.4 Anomaly\n",
    "    is overridden by 'nino_scenario' to enable interactive 'What-If' climate scenario runs.\n",
    "    \"\"\"\n",
    "    np.random.seed(42)  # For reproducibility\n",
    "    \n",
    "    history_len = 60\n",
    "    hist_df = df_ml.dropna(subset=['Rainfall']).tail(history_len).copy()\n",
    "    running_df = hist_df[['Date', 'MaxTemp', 'MinTemp', 'Rainfall']].copy()\n",
    "    \n",
    "    future_dates = future_temp['Date'].values\n",
    "    future_rows = []\n",
    "    \n",
    "    for i, curr_date_np in enumerate(future_dates):\n",
    "        curr_date = pd.to_datetime(curr_date_np)\n",
    "        day_temp = future_temp[future_temp['Date'] == curr_date].iloc[0]\n",
    "        max_temp = day_temp['MaxTemp']\n",
    "        min_temp = day_temp['MinTemp']\n",
    "        \n",
    "        new_row = pd.DataFrame({\n",
    "            'Date': [curr_date],\n",
    "            'MaxTemp': [max_temp],\n",
    "            'MinTemp': [min_temp],\n",
    "            'Rainfall': [np.nan]\n",
    "        })\n",
    "        running_df = pd.concat([running_df, new_row], ignore_index=True)\n",
    "        \n",
    "        # Extract baseline features\n",
    "        month = curr_date.month\n",
    "        doy = curr_date.dayofyear\n",
    "        dow = curr_date.dayofweek\n",
    "        \n",
    "        month_sin = np.sin(2 * np.pi * month / 12)\n",
    "        month_cos = np.cos(2 * np.pi * month / 12)\n",
    "        doy_sin = np.sin(2 * np.pi * doy / 365.25)\n",
    "        doy_cos = np.cos(2 * np.pi * doy / 365.25)\n",
    "        \n",
    "        temp_range = max_temp - min_temp\n",
    "        temp_delta_max = max_temp - running_df.iloc[-2]['MaxTemp']\n",
    "        temp_delta_min = min_temp - running_df.iloc[-2]['MinTemp']\n",
    "        \n",
    "        max_temp_roll3 = running_df.iloc[-3:]['MaxTemp'].mean()\n",
    "        min_temp_roll3 = running_df.iloc[-3:]['MinTemp'].mean()\n",
    "        temp_range_roll3 = (running_df.iloc[-3:]['MaxTemp'] - running_df.iloc[-3:]['MinTemp']).mean()\n",
    "        \n",
    "        rain_lag1 = running_df.iloc[-2]['Rainfall']\n",
    "        rain_lag2 = running_df.iloc[-3]['Rainfall']\n",
    "        rain_lag3 = running_df.iloc[-4]['Rainfall']\n",
    "        \n",
    "        feats_dict = {\n",
    "            'Month': month,\n",
    "            'DayOfYear': doy,\n",
    "            'DayOfWeek': dow,\n",
    "            'Month_Sin': month_sin,\n",
    "            'Month_Cos': month_cos,\n",
    "            'DayOfYear_Sin': doy_sin,\n",
    "            'DayOfYear_Cos': doy_cos,\n",
    "            'TempRange': temp_range,\n",
    "            'TempDeltaMax': temp_delta_max,\n",
    "            'TempDeltaMin': temp_delta_min,\n",
    "            'MaxTemp_Roll3': max_temp_roll3,\n",
    "            'MinTemp_Roll3': min_temp_roll3,\n",
    "            'TempRange_Roll3': temp_range_roll3,\n",
    "            'Rain_Lag1': rain_lag1,\n",
    "            'Rain_Lag2': rain_lag2,\n",
    "            'Rain_Lag3': rain_lag3,\n",
    "            'NINO3.4_Anom': nino_scenario # Set the interactive global ENSO anomaly\n",
    "        }\n",
    "        \n",
    "        feats_df = pd.DataFrame([feats_dict])[features]\n",
    "        prob_rain = clf.predict_proba(feats_df)[:, 1][0]\n",
    "        \n",
    "        # Stochastic Weather Generator (Scale Factor = 1.20)\n",
    "        calibrated_prob = min(0.95, prob_rain * 1.20)\n",
    "        is_rainy = np.random.rand() < calibrated_prob\n",
    "        \n",
    "        if is_rainy:\n",
    "            # Overcast TemperatureFeedback: reduce diurnal temperature range by 25%\n",
    "            temp_range_adj = temp_range * 0.75\n",
    "            max_temp_adj = min_temp + temp_range_adj\n",
    "            running_df.iloc[-1, running_df.columns.get_loc('MaxTemp')] = max_temp_adj\n",
    "            \n",
    "            temp_delta_max_adj = max_temp_adj - running_df.iloc[-2]['MaxTemp']\n",
    "            max_temp_roll3_adj = running_df.iloc[-3:]['MaxTemp'].mean()\n",
    "            temp_range_roll3_adj = (running_df.iloc[-3:]['MaxTemp'] - running_df.iloc[-3:]['MinTemp']).mean()\n",
    "            \n",
    "            feats_dict_adj = feats_dict.copy()\n",
    "            feats_dict_adj['MaxTemp_Roll3'] = max_temp_roll3_adj\n",
    "            feats_dict_adj['TempRange_Roll3'] = temp_range_roll3_adj\n",
    "            feats_dict_adj['TempRange'] = temp_range_adj\n",
    "            feats_dict_adj['TempDeltaMax'] = temp_delta_max_adj\n",
    "            \n",
    "            feats_df_adj = pd.DataFrame([feats_dict_adj])[features]\n",
    "            pred_rain = reg.predict(feats_df_adj)[0]\n",
    "            pred_rain = max(0.2, pred_rain)\n",
    "            \n",
    "            # Inject Gamma/Exponential daily weather residual noise (Noise scale = 2.5 mm)\n",
    "            pred_rain += np.random.exponential(scale=2.5)\n",
    "            pred_rain = min(188.0, pred_rain)\n",
        "        else:\n",
        "            pred_rain = 0.0\n",
        "            \n",
        "        running_df.iloc[-1, running_df.columns.get_loc('Rainfall')] = pred_rain\n",
        "        \n",
        "        future_rows.append({\n",
        "            'Date': curr_date,\n",
        "            'Predicted_MaxTemp': running_df.iloc[-1]['MaxTemp'],\n",
        "            'Predicted_MinTemp': min_temp,\n",
        "            'Rain_Probability': prob_rain,\n",
        "            'IsRainy': 1 if is_rainy else 0,\n",
        "            'Predicted_Rainfall': pred_rain\n",
        "        })\n",
        "        \n",
        "    forecast_df = pd.DataFrame(future_rows)\n",
        "    return forecast_df"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Section 8: Simulating and Comparing 3 Climate Scenarios"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run three scenarios to compare!\n",
    "print(\"1. Simulating La Niña Scenario (NINO3.4 = -1.2 °C) [Moist, cluster storms]...\")\n",
    "df_lanina = predict_future_recursive(df_ml, future_temp, clf, reg, features, nino_scenario=-1.2)\n",
    "\n",
    "print(\"2. Simulating Neutral Scenario (NINO3.4 = 0.0 °C) [Baseline climatology]...\")\n",
    "df_neutral = predict_future_recursive(df_ml, future_temp, clf, reg, features, nino_scenario=0.0)\n",
    "\n",
    "print(\"3. Simulating El Niño Scenario (NINO3.4 = +1.2 °C) [Dry, drought, fire hazard]...\")\n",
    "df_elnino = predict_future_recursive(df_ml, future_temp, clf, reg, features, nino_scenario=1.2)\n",
    "\n",
    "# Export the baseline Neutral forecast to CSV\n",
    "df_neutral.to_csv('hornsby_predicted_rainfall_next_year.csv', index=False)\n",
    "print(\"\\nSuccessfully exported baseline forecast to 'hornsby_predicted_rainfall_next_year.csv'\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Section 9: Visualizing & Comparing Climate Scenarios"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Print comparison stats\n",
    "print(\"=== CLIMATE SCENARIOS COMPARISON ===\")\n",
    "for name, df_sc in [('La Niña', df_lanina), ('Neutral', df_neutral), ('El Niño', df_elnino)]:\n",
    "    tot = df_sc['Predicted_Rainfall'].sum()\n",
    "    days = (df_sc['Predicted_Rainfall'] > 0).sum()\n",
    "    max_r = df_sc['Predicted_Rainfall'].max()\n",
    "    print(f\"{name:<10}: Total Rain = {tot:8.2f} mm | Rainy Days = {days:3d} / 365 | Max Daily Rain = {max_r:6.2f} mm\")\n",
    "    \n",
    "# Plot the cumulative rain paths side-by-side to visually compare\n",
    "plt.figure(figsize=(16, 8))\n",
    "plt.plot(df_lanina['Date'], df_lanina['Predicted_Rainfall'].cumsum(), label='La Niña Scenario (NINO3.4 = -1.2°C) [Wet]', color='#2980b9', linewidth=3.5)\n",
    "plt.plot(df_neutral['Date'], df_neutral['Predicted_Rainfall'].cumsum(), label='Neutral Scenario (NINO3.4 = 0.0°C) [Baseline]', color='#27ae60', linewidth=3)\n",
    "plt.plot(df_elnino['Date'], df_elnino['Predicted_Rainfall'].cumsum(), label='El Niño Scenario (NINO3.4 = +1.2°C) [Dry]', color='#e74c3c', linewidth=3)\n",
    "\n",
    "plt.title('Hornsby Area: Interactive 1-Year Cumulative Rainfall Simulator Path Comparison', fontsize=16, fontweight='bold', pad=15)\n",
    "plt.ylabel('Cumulative Rainfall (mm)', fontsize=13)\n",
    "plt.xlabel('Date', fontsize=13)\n",
    "plt.fill_between(df_lanina['Date'], 0, df_lanina['Predicted_Rainfall'].cumsum(), color='#2980b9', alpha=0.05)\n",
    "plt.fill_between(df_neutral['Date'], 0, df_neutral['Predicted_Rainfall'].cumsum(), color='#27ae60', alpha=0.05)\n",
    "plt.fill_between(df_elnino['Date'], 0, df_elnino['Predicted_Rainfall'].cumsum(), color='#e74c3c', alpha=0.05)\n",
    "\n",
    "plt.legend(fontsize=12, loc='upper left')\n",
    "plt.tight_layout()\n",
    "# Save comparison plot\n",
    "plt.savefig('hornsby_scenarios_comparison.png', dpi=300)\n",
    "plt.show()\n",
    "print(\"Saved climate scenarios comparison plot to 'hornsby_scenarios_comparison.png'\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Section 10: Premium Daily Rainfall Forecast & Heavy Rain Risk Map Visualizer\n",
    "\n",
    "This section provides a standalone, dashboard-quality dark-mode daily rainfall forecast visualizer for the next 365 days.\n",
    "You can specify a custom `threshold` (in mm) to highlight heavy rain events."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_premium_forecast_plot(csv_path='hornsby_predicted_rainfall_next_year.csv', threshold=15.0):\n",
    "    df = pd.read_csv(csv_path)\n",
    "    df['Date'] = pd.to_datetime(df['Date'])\n",
    "    \n",
    "    # 1. Premium Dark Mode Styling Setup (Cinematic Navy-Black Theme)\n",
    "    plt.style.use('dark_background')\n",
    "    \n",
    "    bg_color = '#070a13'       # Rich Dark Cinematic Blue-Black\n",
    "    card_color = '#0f172a'     # Card Background Navy-Slate\n",
    "    accent_blue = '#38bdf8'    # Neon Cyan/Sky Blue\n",
    "    accent_rose = '#f43f5e'    # Neon Rose/Pink (for heavy rain)\n",
    "    grid_color = '#1e293b'     # Thin Slate Divider\n",
    "    text_color = '#f8fafc'     # Pure White-Slate\n",
    "    text_muted = '#64748b'     # Muted grey-slate\n",
    "    border_color = '#334155'   # Glassmorphic border slate\n",
    "    \n",
    "    fig, ax = plt.subplots(figsize=(18, 9.5), facecolor=bg_color)\n",
    "    ax.set_facecolor(bg_color)\n",
    "    \n",
    "    # 2. Multi-Pass Neon Glow Daily Rainfall Bars\n",
    "    # Deep outer glow (widest line, ultra-low opacity)\n",
    "    ax.vlines(\n",
    "        df['Date'], 0, df['Predicted_Rainfall'],\n",
    "        colors='#0284c7', alpha=0.12, linewidth=6.0, zorder=1\n",
    "    )\n",
    "    # Mid glow (medium line, low opacity)\n",
    "    ax.vlines(\n",
    "        df['Date'], 0, df['Predicted_Rainfall'],\n",
    "        colors='#0ea5e9', alpha=0.35, linewidth=3.5, zorder=2\n",
    "    )\n",
    "    # Core neon bar (thin line, high opacity)\n",
    "    ax.vlines(\n",
    "        df['Date'], 0, df['Predicted_Rainfall'],\n",
    "        colors=accent_blue, alpha=0.90, linewidth=1.5, label='Daily Predicted Rainfall', zorder=3\n",
    "    )\n",
    "    \n",
    "    # Fill the area under the timeline slightly for a modern glow effect\n",
    "    ax.fill_between(\n",
    "        df['Date'], 0, df['Predicted_Rainfall'],\n",
    "        color=accent_blue, alpha=0.04, zorder=1\n",
    "    )\n",
    "    \n",
    "    # 3. Dynamic Banded Weather Risk Zones (Background Gradients)\n",
    "    y_max = df['Predicted_Rainfall'].max() + 8\n",
    "    ax.set_ylim(0, y_max)\n",
    "    \n",
    "    # Heavy Rain Risk Zone (Above Threshold)\n",
    "    ax.axhspan(threshold, y_max, color=accent_rose, alpha=0.025, zorder=0)\n",
    "    ax.text(\n",
    "        df['Date'].min() + pd.Timedelta(days=5), threshold + 1.2,\n",
    "        \"HEAVY RAIN RISK ZONE (>= 15.0 mm)\",\n",
    "        color=accent_rose, fontsize=10, fontweight='bold', alpha=0.7, zorder=4\n",
    "    )\n",
    "    \n",
    "    # Moderate Rain Zone (5mm - Threshold)\n",
    "    ax.axhspan(5.0, threshold, color='#0ea5e9', alpha=0.012, zorder=0)\n",
    "    ax.text(\n",
    "        df['Date'].min() + pd.Timedelta(days=5), 6.0,\n",
    "        \"MODERATE RAIN ZONE (5.0 - 15.0 mm)\",\n",
    "        color=accent_blue, fontsize=10, fontweight='bold', alpha=0.5, zorder=4\n",
    "    )\n",
    "    \n",
    "    # 4. Identify and Highlight Heavy Rain Events (with 4-Layer Glow Starbursts)\n",
    "    heavy_rain_df = df[df['Predicted_Rainfall'] >= threshold]\n",
    "    heavy_count = len(heavy_rain_df)\n",
    "    \n",
    "    if heavy_count > 0:\n",
    "        # Layer 1: Broad Outer Glow\n",
    "        ax.scatter(\n",
    "            heavy_rain_df['Date'], heavy_rain_df['Predicted_Rainfall'],\n",
    "            color=accent_rose, s=500, zorder=4, alpha=0.10\n",
    "        )\n",
    "        # Layer 2: Medium Halo\n",
    "        ax.scatter(\n",
    "            heavy_rain_df['Date'], heavy_rain_df['Predicted_Rainfall'],\n",
    "            color=accent_rose, s=220, zorder=5, alpha=0.35\n",
    "        )\n",
    "        # Layer 3: Neon Rose point\n",
    "        ax.scatter(\n",
    "            heavy_rain_df['Date'], heavy_rain_df['Predicted_Rainfall'],\n",
    "            color=accent_rose, s=80, zorder=6, alpha=0.9,\n",
    "            edgecolors='#ffffff', linewidths=0.8, label=f'Heavy Rain (>= {threshold}mm)'\n",
    "        )\n",
    "        # Layer 4: Bright Core Center\n",
    "        ax.scatter(\n",
    "            heavy_rain_df['Date'], heavy_rain_df['Predicted_Rainfall'],\n",
    "            color='#ffffff', s=20, zorder=7, alpha=1.0\n",
    "        )\n",
    "        \n",
    "        # Annotate and target the heaviest rainfall event\n",
    "        heaviest_day = heavy_rain_df.loc[heavy_rain_df['Predicted_Rainfall'].idxmax()]\n",
    "        \n",
    "        # Draw target ring on the heaviest day\n",
    "        ax.scatter(\n",
    "            [heaviest_day['Date']], [heaviest_day['Predicted_Rainfall']],\n",
    "            facecolors='none', edgecolors=accent_rose, s=900, linewidths=1.5, zorder=8, alpha=0.8\n",
    "        )\n",
    "        \n",
    "        # Custom glassmorphic popup annotation\n",
    "        ax.annotate(\n",
    "            f\"  PEAK SYSTEM EVENT\\n  Rain: {heaviest_day['Predicted_Rainfall']:.1f} mm\\n  Date: {heaviest_day['Date'].strftime('%d %b %Y')}  \",\n",
    "            xy=(heaviest_day['Date'], heaviest_day['Predicted_Rainfall']),\n",
    "            xytext=(heaviest_day['Date'] + pd.Timedelta(days=12), heaviest_day['Predicted_Rainfall'] + 2.5),\n",
    "            color=text_color,\n",
    "            fontweight='bold',\n",
    "            fontsize=10.5,\n",
    "            zorder=10,\n",
    "            bbox=dict(boxstyle=\"round,pad=0.6,rounding_size=0.2\", facecolor='#1e1b4b', edgecolor=accent_rose, alpha=0.9, linewidth=1.5),\n",
    "            arrowprops=dict(arrowstyle=\"->\", color=accent_rose, lw=2.0, connectionstyle=\"arc3,rad=0.2\")\n",
    "        )\n",
    "        \n",
    "    # 5. Draw the Threshold Line\n",
    "    ax.axhline(\n",
    "        y=threshold, color=accent_rose, linestyle='--', linewidth=1.5, alpha=0.7,\n",
    "        label=f'Heavy Rain Threshold ({threshold} mm)', zorder=4\n",
    "    )\n",
    "    \n",
    "    # 6. Fine-tune Axes and Grid Lines\n",
    "    ax.xaxis.set_major_locator(mdates.MonthLocator(interval=1))\n",
    "    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))\n",
    "    plt.xticks(rotation=25, ha='right', color=text_muted, fontsize=11)\n",
    "    plt.yticks(color=text_muted, fontsize=11)\n",
    "    \n",
    "    ax.spines['top'].set_visible(False)\n",
    "    ax.spines['right'].set_visible(False)\n",
    "    ax.spines['left'].set_color(grid_color)\n",
    "    ax.spines['bottom'].set_color(grid_color)\n",
    "    ax.spines['left'].set_linewidth(1.2)\n",
    "    ax.spines['bottom'].set_linewidth(1.2)\n",
    "    \n",
    "    # Elegant gridlines\n",
    "    ax.grid(color=grid_color, linestyle='--', linewidth=0.6, alpha=0.6)\n",
    "    \n",
    "    # Title Block\n",
    "    plt.title(\n",
    "        'Hornsby Area: 365-Day Daily Rainfall Forecast & Heavy Rain Risk Map',\n",
    "        fontsize=18, fontweight='bold', color=text_color, pad=25, loc='left'\n",
    "    )\n",
    "    \n",
    "    ax.set_ylabel('Rainfall Intensity (mm)', color=text_color, fontsize=13, labelpad=12)\n",
    "    ax.set_xlabel('Forecast Timeline', color=text_color, fontsize=13, labelpad=12)\n",
    "    \n",
    "    # 7. Premium Glassmorphic Dashboard Summary Panel\n",
    "    total_annual = df['Predicted_Rainfall'].sum()\n",
    "    rainy_days = (df['Predicted_Rainfall'] > 0).sum()\n",
    "    \n",
    "    summary_text = (\n",
    "        f\"  FORECAST STATS\\n\"\n",
    "        f\"  ====================\\n\"\n",
    "        f\"  Range: May 2026 - Apr 2027\\n\"\n",
    "        f\"  Total Rain: {total_annual:.1f} mm\\n\"\n",
    "        f\"  Wet Days: {rainy_days} / 365\\n\"\n",
    "        f\"  Heavy Days: {heavy_count} days\"\n",
    "    )\n",
    "    \n",
    "    # Draw a box for the summary panel (Navy slate with bright borders)\n",
    "    props = dict(boxstyle='round,pad=0.8,rounding_size=0.25', facecolor=card_color, edgecolor=border_color, alpha=0.9, linewidth=1.2)\n",
    "    ax.text(\n",
    "        0.02, 0.95, summary_text, transform=ax.transAxes, fontsize=11,\n",
    "        verticalalignment='top', bbox=props, color=text_color, linespacing=1.65, fontweight='medium', zorder=9\n",
    "    )\n",
    "    \n",
    "    # Legend\n",
    "    legend = ax.legend(\n",
    "        loc='upper right', facecolor=card_color, edgecolor=border_color,\n",
    "        labelcolor=text_color, fontsize=11, framealpha=0.9, borderpad=0.8\n",
    "    )\n",
    "    legend.get_frame().set_linewidth(1.2)\n",
    "    legend.set_zorder(9)\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    output_path = 'hornsby_forecast_premium.png'\n",
    "    plt.savefig(output_path, dpi=300, facecolor=bg_color)\n",
    "    plt.show()\n",
    "\n",
    "# Generate the plot inside the notebook!\n",
    "generate_premium_forecast_plot(threshold=15.0)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('hornsby_rainfall_predication_v2.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)
print("Updated hornsby_rainfall_predication_v2.ipynb successfully with Section 10!")
